### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brycetheman** [LoseBypass/issues#17]
**Describe the bug**
the black and white screen with rendering features enabled and hud features enabled also when on optifine. 

**To Reproduce**
Steps to reproduce the behavior: on vanilla fast math and render need to be off for the hud features to work and on optifine it doesn’t work at all.

1. Go to 'Options >> video settings >> performance'
2. Click on 'fast render and fast math to turn it off and fix on vanilla'
3. See error

**Expected behavior**
On vanilla it will work with both off but when in optifine it will be white at first with just fast render off then when turning fast math off it turns black and no fix after that.

**Desktop**
- OS: [Windows 10] (latest version)

**Additional context**
its been a main bug since i bought because i kinda need optifine for fps my pc is trash and the rendering settings help with fps too.

**Comment by surge541** [comment]
Sorry, this isn't solvable :(
