### ISSUE TITLE
[BUG] Randomly crash / freeze 😭

### ISSUE THREAD

**Issue by bhop0** [LoseBypass/issues#2]
**Describe the bug**
Title

**To Reproduce**

1. Launch Breeze (optifine, beta mode)
2. Play normally
3. Crash / Freeze

**Expected behavior**
Stable

**Screenshots**
No

**Desktop:**

- OS: Windows 10 22H2 19045.3448

**Additional context**
The crash/freeze doesn't seem to have any cause... 😓 sry for that

**Comment by Wolfsurge** [comment]
Can you attach a log?

**Comment by bhop0** [comment]
> Can you attach a log?

[crash-2023-10-05_14.31.31-client.txt](https://github.com/LoseBypass/issues/files/12818681/crash-2023-10-05_14.31.31-client.txt)

**Comment by Wolfsurge** [comment]
OK, this is because of a theme. Another issue (#3) whic you also made fixes this. Basically, in one of your themes, there is a duplicate value of 'blur'. Just remove whichever line that is and the issue should fix itself.
