### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by j-Z52** [LoseBypass/issues#22]
**Describe the bug**
Every time I relaunch the client, favorites modules disappear (are unfavorited). 

**To Reproduce**

1. Go to 'Modules'
2. Favorite any module/modules
3. Close the client
4. Relaunch the client 

**Expected behavior**
The favorites stay after relaunch or maybe are inside a config?

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: MacOS Sonoma

**Additional context**
On latest version of Breeze for Forge. Only mod I am using with it is Optifine.

**Comment by surge541** [comment]
Fix will be available in the next update
