### ISSUE TITLE
[BUG] Joining a server crashes

### ISSUE THREAD

**Issue by 0xhis** [LoseBypass/issues#32]
**Describe the bug**
Joining a server crashes, I am using essential with Optifine and ReplayMod.

**To Reproduce**

1. Use essential 1.8.9
2. Inject Breeze
3. Attempt to join a server
4. Get kicked

**Expected behavior**
I should join the server with no crashes.

**Desktop (please complete the following information):**

- OS: Windows 11 23H2

**Additional context**
Error when Minecraft crashes : `The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error`

Using injectable breeze

[latest.log](https://github.com/LoseBypass/issues/files/15049721/latest.log)

**Comment by wallhacks0** [comment]
will not fix

**Comment by 0xhis** [comment]
alr
