### ISSUE TITLE
[BUG] Autoclicker only clicking 10 cps with NoHitDelay on

### ISSUE THREAD

**Issue by davedberry2** [LoseBypass/issues#38]
**Describe the bug**
the auto clicker not clicking above 10 cps. on servers like anticheat-test.com it says the cps is 10, I modified the cps script to listen for C0APacketAnimation and it also says 10cps.

**To Reproduce**

enable autoclicker with min and max above 10 cps

**Expected behavior**
the clicker will click the desired cps

**Screenshots**
![image](https://github.com/LoseBypass/issues/assets/54686916/b6d2f55a-cfe2-401b-b1ef-5dd1420e2d13)

**Desktop (please complete the following information):**

- OS: windows 10 and zorin os (linux)

**Additional context**
It does not matter if i have NoHitDelay on or look at a player it will still click only 10 cps. I think the issue is that you're using a timer to check if a certain number of milliseconds has elapsed during a motion or tick event.(I made this mistake before). it happens because there are only 20 ticks so some of the milliseconds are not on time

**Comment by wallhacks0** [comment]
fixed next update thanks for reporting!
